### ISSUE TITLE
New version of CPU automatically handles installation

### ISSUE THREAD

**Issue by altf4** [Atokigedesu/cpu-level-11-setup-script#2]
Try out this commit: afc025555e28aa0c66be0c7c9f2a5aa39a63c92e

Most of the setup should be taken care of automatically now. Is your script still required? I'm trying to make installation as easy as possible.

Thanks!

**Comment by Atokigedesu** [comment]
@altf4 
The great commit! It is enough helpful for everyone, so I will deprecate this repository.

Good luck on your development! :smile:

**Comment by Atokigedesu** [comment]
closed by 202c536599a2dcbc4411aa111a79f73b15e20740
